### PR TITLE
Portuguese

### PR DESCRIPTION
**Pull request by dchelimsky**
WIP - I'm about 1/4 of the way through. Not ready for public comment, but I just wanted you to know this is in progress.

### CODE REVIEW

**Comment by NaokoHigashide** [comment]
Thanks, David!  And Flore!

**Comment by dchelimsky** [comment]
OK. This is ready for review/merge. We got some assistance from Flor's niece, Amarilis Iscold, who also lives in the US (fluent in both languages) and helped a ton!

**Comment by gauraklein** [comment]
Thanks so much to you all, what a team!

**Comment by dchelimsky** [comment]
We were all happy to help @Gauraklein.

Please let us know if any of the English needs to change and we'll update the Portuguese to follow suit.

**Comment by gauraklein** [comment]
Will do, thanks again!

**Pull request merged**
