### PR TITLE
Add Vietnamese language file

### PR DESCRIPTION
**Pull request by KingMob**
Translated courtesy of Julie Huynh-Rusk and Benjamin Huynh, PR submitted by Matthew Davidson of Cognitect.

Also includes source Excel spreadsheet used by translators as a reference. Additions and changes made on Apr 3rd were incorporated over email.

While Julie is a professional translator, and she ran her translations by a Vietnamese physician, since these translations are not being certified, she offered the following disclaimer, in both English and Vietnamese, if you wish to display it.

> "We have translated this to the best of our abilities, but we are not medical professionals and cannot guarantee the translation. The hospital's linguist should review everything to be sure it is good to go." 

> "Chúng tôi đã dịch điều này với khả tất cả khả năng của mình, nhưng vì chúng tôi không phải là dịch giả y tế chuyên nghiệp, nên không thể đảm bảo bản dịch đúng. Do đó, những thông dịch chuyên nghiệp về y khoa của bệnh viện mới có đủ thẩm quyền để bảo đảm mọi thứ là đúng."

### CODE REVIEW

**Comment by gauraklein** [comment]
Thank you so much Julie, Benjamin and Matthew!!

**Comment by KingMob** [comment]
Thanks @Gauraklein. Can you let me know when it's ready to share with Julie? I figured she'd like to see her work on the screen and/or double-check it.

**Comment by gauraklein** [comment]
@KingMob Definitely will :)

**Comment by gauraklein** [comment]
@KingMob translations are live on the site now! 
[https://checkforcorona.com/#/screening](url) 
Thanks again for all your hard work :)

**Pull request merged**
