### PR TITLE
Create ko.edn #8

### PR DESCRIPTION
**Pull request by semper21**
Copied in strings from Word docs `"MW1060368_Luminare questions_KO.docx"` and `"MW1060368_Clean Copy 8P 0322 COVID19 Luminare Mods_KO.docx."` Did not map strings that were not present in the docs. 

A few things of note: 
- Due to the nature of Korean, many links/phone numbers needs to be left in as part of strings. 
- The current mapping of the key names `:outcome-panel/visit` and `:outcome-panel/for-frequent-updates` is technically incorrect. The translation in Korean is written as: "[links] by visiting // get frequent updates // " instead of "visit [links] // for frequent updates" in English. If the link is put in between the two keys, the Korean text would not make much sense.
- Another similar issue: Right now, `:outcome-panel/contact-nurse-triage` and `:outcome-panel/for-further-evaluation` make up one sentence but are divided (I'm assuming because of the phone number in between the two). In Korean the order needs to be reversed. But in this case it will still be comprehensible as long as the two phrases stay in one line/sentence and the phone number stays where it is. 
- There was a typo in `:factor-question/any-of-the-following` and `:factor-question/allergies` (same Korean string). I fixed it 준 -> 중 

Please let me know if you need clarification or have questions

### CODE REVIEW

**Comment by adamfeldman** [comment]
Oops, I was wrong -- the commit message referencing #8 didn't link it, so I am making this comment (next time I will remember that issue references *will* work in PR comments)

**Comment by adamfeldman** [comment]
Thank you @semper21 for the detailed comments!

**Comment by oakmac** [comment]
This is really wonderful @semper21 - thank you so much for the contribution!

I created Issue #10 and Issue #11 as follow-up for the questions you raise here. Will also look for other places in the translation strings where some variable interpolation makes sense.

I am going to merge this, tweak it a bit for the CI process to pass, then get these ported into the app.

**Comment by oakmac** [comment]
@semper21 and @adamfeldman - the Korean translations are live on the production site now :tada: 

Thank you so much for the contribution here :heart: 

There are some follow-up issues #10 and #11 if you have the bandwidth.

**Comment by semper21** [comment]
@oakmac Great! I addressed issues #10 and #11 (see #13). I also found a few typos - will make changes once #13 gets merged! 

P.S. I can also help with translating rest of the texts if need be!

**Comment by oakmac** [comment]
> I can also help with translating rest of the texts if need be!

This would be very helpful - thank you!

**Pull request merged**
